---
- name: Create directory /home/backup/mysql
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: '0700'
          
- name: Add MySQL backup user
  community.mysql.mysql_user:
    name: backup
    password: "{{ mysql_backup_password }}"
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  #no_log: True

- name: Add .my.cnf
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0700'
  notify: Restart MySQL
  #no_log: True

- name: Create Cron tab
  template:
    src: mysql-backup-cron
    dest: /etc/cron.d/mysql-backup
