---
- name: Install uWSGI packages
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: latest

- name: Add the uWSGI configuration for AGAMA
  copy:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI

- name: Ensure that uWSGI is started
  service:
    name: uwsgi
    state: started
    enabled: yes
