---
- name: Install uWSGI packages
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: latest

- name: Add the uWSGI configuration for AGAMA
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI

- name: Run uWSGI
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
