---
- name: Initial
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - init
    - node_exporter
  tags:
    - init

- name: Backups
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - backup
  tags:
    - backup

- name: DNS Server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
    - bind_exporter
  tags:
    - dns

- name: DNS records
  hosts: dns_masters
  become: yes
  gather_facts: no
  roles:
    - dns_records
  tags:
    - drec

- name: systemd-resolved
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - systemd-resolved
  tags:
    - sysd

- name: Nginx
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - nginx
    - nginx_exporter
  tags:
    - nginx

- name: Database Server
  hosts: application_stack
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_backup
    - mysql_exporter
  tags:
    - db

- name: Docker
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - docker
  tags:
    - docker

- name: Web Server
  hosts: application_stack
  become: yes
  gather_facts: no
  roles:
    - agama
  tags:
    - agama

- name: Logging
  hosts:
    - internal_services
  become: yes
  gather_facts: no
  roles:
    - prometheus
    - pinger
  tags:
    - log

- name: InfluxDB
  hosts:
    - internal_services
  become: yes
  gather_facts: no
  roles:
    - influxdb
    - telegraf
    - influxdb_exporter
    - influxdb_backup
  tags:
    - influx

- name: Grafana
  hosts:
    - internal_services
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags:
    - grafana

- name: Rsyslog
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - rsyslog
  tags:
    - rsys

- name: HAProxy & Keepalived
  hosts: application_stack
  become: yes
  roles:
    - keepalived
    - keepalived_exporter
    - haproxy
    - haproxy_exporter
  tags:
    - ha
