{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"linux\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=~\"linux\"}[30d]) + avg_over_time(node_memory_Cached_bytes{job=~\"linux\"}[30d]) + avg_over_time(node_memory_Buffers_bytes{job=~\"linux\"}[30d])) / avg_over_time(node_memory_MemTotal_bytes{job=~\"linux\"}[30d])))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL Q/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])"
    }
   ]
  },
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "Bind9 Q/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (rate(bind_resolver_queries_total[1m]))"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Nginx Q/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  }
 ]
}