---
- name: Creat directory /opt/agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download Agama Docker container
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Download Agama
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama

- name: Build Agama Docker container
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Run Agama Docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: "agama-{{ item.value }}"
    image: agama
    published_ports: "{{ agama_port_base + item.value }}:8000"
    restart_policy: always
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
  loop: "{{ agama_ports | dict2items }}"
  no_log: True