---
- name: Create user agama
  ansible.builtin.user:
    name: agama

- name: Create directory /opt/agama
  ansible.builtin.file:
    path: /opt/agama
    owner: agama
    state: directory

- name: Install application dependencies
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql
    state: latest

- name: Install Agama
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
