---
- name: Creat directory /opt/agama
  file:
    path: /opt/agama
    state: directory

- name: Download Agama Docker container
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Download Agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama

- name: Build Agama Docker container
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Run Agama Docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: agama
    image: agama
    published_ports: "8001:8000"
    restart_policy: always
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
  #no_log: True