---
- name: Stop service "systemd-resolved"
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Replace resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
