---
- name: Create directory /home/backup/influxdb
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    mode: '0700'

- name: Upload file /etc/cron.d/influxdb-backup
  ansible.builtin.template:
    src: influxdb-backup-cron.j2
    dest: /etc/cron.d/influxdb-backup
