---
- name: Create directory /home/backup/influxdb
  file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    mode: '0700'

- name: Upload file /etc/cron.d/influxdb-backup
  template:
    src: influxdb-backup-cron
    dest: /etc/cron.d/influxdb-backup
