---
- name: Install fping
  ansible.builtin.apt:
    name: fping
    state: latest

- name: Create user pinger
  ansible.builtin.user:
    name: pinger

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /usr/local/bin/pinger
    - /etc/pinger/

- name: Upload pinger script
  ansible.builtin.copy:
    src: pinger.sh
    dest: /usr/local/bin/pinger/pinger.sh
    mode: '0777'
  notify: Daemon reload

- name: Upload pinger config
  ansible.builtin.template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify: Daemon reload

- name: Upload file pinger service
  ansible.builtin.copy:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
    mode: '0777'
  notify: Daemon reload

- meta: flush_handlers

- name: Start pinger
  ansible.builtin.service:
    name: pinger
    state: started
    enabled: yes
