---
- name: install unzip
  apt:
    name: unzip
    state: latest

- name: Download Keepalived exporter
  ansible.builtin.unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.2.0/keepalived-exporter-1.2.0.linux-amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    mode: 755

- name: Upload file /etc/systemd/system/keepalived_exporter.service
  copy:
    src: keepalived_exporter.service
    dest: /etc/systemd/system/keepalived_exporter.service
    mode: '0777'
  notify: Daemon reload

- meta: flush_handlers

- name: Run Keepalived exporter
  service:
    name: keepalived_exporter
    state: started
    enabled: yes
