---
- name: Install HAProxy exporter
  apt:
    name: prometheus-haproxy-exporter
    state: latest

- name: Run HAProxy exporter
  service:
    name: prometheus-haproxy-exporter
    state: started

- name: Upload file /etc/default/prometheus-haproxy-exporter
  template:
    src: prometheus-haproxy-exporter
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart HAProxy exporter
