---
- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: latest
          
- name: Update Prometheus jobs
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Add argument to Prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart Prometheus
