---
- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Run Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
