---
- name: Install Telegraf
  ansible.builtin.apt:
    name: telegraf
    state: latest
  register: telegraf_installed

- name: Update Telegraf configuration
  ansible.builtin.copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart Telegraf

- name: Run Telegraf
  ansible.builtin.service:
    name: telegraf
    state: started
  when: telegraf_installed.changed
